TESTS WITH ERRORS 
test13 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 373, in test13
    self.assertTrue(str(answer1[0]).startswith("No bindings"))
IndexError: list index out of range

test14 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 405, in test14
    KB.kb_retract(fact2)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/student_code.py", line 146, in kb_retract
    f = self.facts[self.facts.index(f)]
ValueError: Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [], [], []) is not in list

-------------------------------
TESTS FAILED  
test10 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 282, in test10
    self.assertFalse(answer2)
AssertionError: True is not false

test5 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 151, in test5
    self.assertTrue(len(answer4) > 0)
AssertionError: False is not true

-------------------------------
TESTS SKIPPED 
-------------------------------
